version: "3.1"

services: 
  app1:
    stdin_open: true
    build: app1/app1
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000
      
  app2:
    stdin_open: true
    build: app2/app2
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000

  micro-frontend-nginx:
    container_name: micro-frontend-nginx
    build: nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "8080:80"
    networks:
      - local-network
    depends_on:
      - app1
      - app2

networks:
  local-network: